version: '3'

services:
  app_curer:
    restart: always
    build: ./curer



  nginx:
    image: nginx:1.17
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      # - ./data/certbot/conf:/etc/letsencrypt
      ## - ./data/certbot/www:/var/www/certbot
    depends_on:
      - app_curer
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"